# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config=build_blockers.flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --config=warn_only.flake8 --exit-zero
    - name: Test with pytest
      run: |
        pytest
    - name: Upload pytest-cov coverage HTML
      uses: actions/upload-artifact@v1
      with:
        name: pytest-coverage-report-html
        path: coverage_html
      if: ${{ always() }}
    - name: Upload pytest-cov coverage XML
      uses: actions/upload-artifact@v1
      with:
        name: pytest-coverage-report-xml
        path: coverage.xml
      if: ${{ always() }}
